### ISSUE TITLE
SOLCjs to use webworker

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#135]
- fix solcjs compiler to use webworker

**Comment by alincode** [comment]
<https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers>

**Comment by alincode** [comment]
https://github.com/ethereum-play/editor-solidity/blob/master/src/editor-solidity.js#L63

https://www.youtube.com/watch?v=HcSqj1apNHI

**Comment by serapath** [comment]
Currently we have 1 module (solc-js) and we need is 2 more modules:

1. solc-js-webworker (which does `require('solc-js')`)
    * and it get's loaded in a web worker
    * listens to messages like:
      ```js
        onmessage = event => {
          const [msgID, from, path, ref, type, body] = event.data
        }
      ```
    * and it receives messages and calls solc-js methods
2. solc-js-proxy
    * it loads a web worker with solc-js-webworker
    * it offers the same methods as solc-js
    * it forwards method calls to the webworker
      ```js
        solcjs_worker.postMessage([msgID, from, path, ref, type, body])
      ```
    * it listens for responses from the webworker
      ```js
        solcjs_worker.onmessage = event => {
          const [msgID, from, path, ref, type, body] = event.data
        }
      ```
    * it responds to the original method call with the result, so `solc-js` methods need to be `async/await`
