### ISSUE TITLE
use public test chain, it need to waiting very long time to get callback.

### ISSUE THREAD

**Issue by alincode** [ethereum/play#23]
## `@todo`
* [x] use public test chain, it need to waiting very long time to get callback.

---
![2018-08-17 16 30 47](https://user-images.githubusercontent.com/7610755/44256163-f2328480-a23a-11e8-893e-8db23afedcb6.png)

![2018-08-17 16 32 21](https://user-images.githubusercontent.com/7610755/44256262-39b91080-a23b-11e8-9717-aa81c7a88e5f.png)

**Comment by alincode** [comment]
https://github.com/oraclize/ethereum-bridge
https://github.com/oraclize/truffle-starter

**Comment by alincode** [comment]
![2018-08-24 12 14 25](https://user-images.githubusercontent.com/7610755/44564786-8484dc00-a797-11e8-9f62-ff178078d840.png)

![2018-08-24 12 14 55](https://user-images.githubusercontent.com/7610755/44564796-8c448080-a797-11e8-986f-ca2136039a9a.png)

![2018-08-24 12 15 30](https://user-images.githubusercontent.com/7610755/44564799-949cbb80-a797-11e8-949a-d11581732a24.png)

**Comment by alincode** [comment]
it's work now.

**Comment by serapath** [comment]
is this issue resolved? ...what is left to be done?
