### ISSUE TITLE
2018.12.05-17:00Z | content planning

### ISSUE THREAD

**Issue by serapath** [ethereum/play#74]
# AGENDA
`location` https://meet.jit.si/play
## SPECIFICS:
1. [x] explain the play project
2. [x] show how to use the workshop module for content (for @ChrisChinchilla)
2. [x] learn about @bit-shift's Solidity tour project
3. [x] talk about integration of testing solidity exercise results
4. [x] come up with "next steps" (what will we maybe do together?)

**Comment by serapath** [comment]
# `2018.12.05` Meeting Notes

## Next Steps
* [#75 exercise/lesson validation (dressed as a "virtual customer" regarding the user experience)](https://github.com/ethereum/play/issues/75)

**Comment by ChrisChinchilla** [comment]
I will try recording some video after 0.5.2 release
