### ISSUE TITLE
refactory solcjs module

### ISSUE THREAD

**Issue by alincode** [ethereum/play#77]
## `@todo`
* [x] modularize compiler code
* [ ] minimize code
* [x] implement module API as specified below

---
**Is your feature request related to a problem? Please describe.**
* it should be able support all version, and easy to expand.

**Describe the solution you'd like**
* split big function, make it more easy to testable
  * [Ask Stack: Is it OK to split into small functions, even if they’re called once?](https://arstechnica.com/information-technology/2013/08/ask-stack-is-it-ok-to-split-into-small-functions-even-if-theyre-called-once/)
* add test case
* use promise wrap public function

**Describe alternatives you've considered**

**Additional context**

@serapath advice todo

```
1. solcjs.version2url --->  await solcjs.versions
2. solcjs ---> await solcjs
3. compiler ---> await compiler
4. add compiler.version function return { name: '', url: ''}
```

**Comment by serapath** [comment]
haha :-) when you click **`new issue`** there is a small link below [Don’t see your issue here? Open a regular issue.](https://github.com/ethereum/play/issues/new) which allows you to open an issue without a template.

**Comment by serapath** [comment]
**I checked your modules:**

1. i like those:
https://www.npmjs.com/package/ajax-caching
https://www.npmjs.com/package/solc-version

2. not yet sure - need to see an example how they work with the compiler import callback
https://www.npmjs.com/package/solc-import
https://www.npmjs.com/package/solc-resolver
(also how they would look like if they would use many small resolver modules for each backend (e.g. swarm, github, ipfs, etc...)

3. i wish this one would be much more raw and minimal:
https://www.npmjs.com/package/solcjs-core

4. I am not yet sure about this one - depends on `solcjs-core` which would be cool if it was more minimal
https://www.npmjs.com/package/solcjs-lightweight

**Comment by alincode** [comment]
@serapath 

implement a small resolver module

```js
const ResolverEngine = require('solc-resolver').ResolverEngine;
let resolverEngine = new ResolverEngine();
let resolveGithub = require('resolve-github');
resolverEngine.addResolver(resolveGithub);
let resolveIpfs = require('resolve-ipfs');
resolverEngine.addResolver(resolveIpfs);

const getImportContent = async function (path) {
  return myDB.has(path) ? myDB.get(path) : await resolverEngine.require(path);
};

let output = await compiler(sourceCode, getImportContent);
```
